# Book settings
title: Imperfect Summaries 
author: Michael McCarrin
exclude_patterns: [README.md]

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib
# Information about where the book exists on the web
repository:
  url                       : https://github.com/gramlogic/metabias/
  branch: master  # An optional branch, defaults to `master`

html:
  use_repository_button: true
  use_edit_page_button: true
